CREATE TABLE IF NOT EXISTS people (
	id int8 GENERATED BY DEFAULT AS IDENTITY,
	user_id int8 NULL,
	full_name varchar(150) NOT NULL,
	
	CONSTRAINT people_pkey PRIMARY KEY (id),
	CONSTRAINT people_user_id_key UNIQUE (user_id),
	CONSTRAINT people_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS natural_people (
	id int8 NOT NULL,
	birth_date date NOT NULL,	
	ssn varchar(20) NOT NULL, -- Brasil CPF Formato: 123.456.789-09, America SSN Formato: 123-45-6789
	gender varchar(20) NULL,
	marital_status varchar(20) NULL,
	nationality varchar(50) NULL,
	professional_occupation varchar(100) NULL,
	
	CONSTRAINT natural_people_pkey PRIMARY KEY (id),
	CONSTRAINT natural_people_gender_check  CHECK (gender IN ('MALE', 'FEMALE', 'NON_BINARY', 'OTHER')),
	CONSTRAINT natural_people_ssn_key UNIQUE (ssn),
	CONSTRAINT natural_people_people_fk FOREIGN KEY (id) REFERENCES people(id)
);

CREATE TABLE IF NOT EXISTS legal_entities (
	id int8 NOT NULL,
	trade_name varchar(150) NULL,
	ein varchar(18) NOT NULL,
	foundation_date date NULL,
	municipal_registration varchar(20) NULL,
	state_registration varchar(20) NULL,
	company_size varchar(30) NULL,
	legal_nature varchar(100) NULL,
	primary_activity varchar(100) NULL,
	secondary_activities varchar(500) NULL,
	
	CONSTRAINT legal_entities_pkey PRIMARY KEY (id),
	CONSTRAINT legal_entities_ein_key UNIQUE (ein),
	CONSTRAINT egal_entities_people_fk FOREIGN KEY (id) REFERENCES people(id)
);


CREATE TABLE IF NOT EXISTS addresses (
	id int8 GENERATED BY DEFAULT AS IDENTITY,
	people_id int8 NOT NULL,
	address_type varchar(255) NOT NULL,
	zip_code varchar(8) NULL,
	street varchar(150) NULL,
	"number" varchar(10) NULL,
	complement varchar(50) NULL,
	district varchar(50) NULL,
	city varchar(50) NULL,
	state varchar(2) NULL,
	country varchar(30) NULL,	
	is_primary bool NULL,
	
	CONSTRAINT addresses_pkey PRIMARY KEY (id),
	CONSTRAINT addresses_address_type_check CHECK (address_type IN ('RESIDENTIAL', 'BILLING', 'DELIVERY', 'COMMERCIAL', 'OTHER')),
	CONSTRAINT addresses_people_id_fk FOREIGN KEY (people_id) REFERENCES people(id)
);

CREATE TABLE IF NOT EXISTS contacts_info (
	id int8 GENERATED BY DEFAULT AS IDENTITY,
	people_id int8 NOT NULL,
	conatct_type varchar(150) NULL,
	"name" varchar(150) NULL,
	phone varchar(20) NULL,
	email varchar(100) NULL,
	is_primary bool NULL,
	
	CONSTRAINT contact_info_pkey PRIMARY KEY (id),
	CONSTRAINT contact_info_people_id_fk FOREIGN KEY (people_id) REFERENCES people(id)
);




