spring.application.name=attendance
spring.profiles.active=dev

jwt.secret=_ads.l=kj2779698a@#$hnlï¿½kjhdf@#!
jwt.expiration.user.min=30
jwt.expiration.user.activation.min=1200
jwt.expiration.user.reset.password.min=30